// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: heartbeat/heartbeat.proto

package heartbeat

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PONEResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PONEResponse) Reset() {
	*x = PONEResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heartbeat_heartbeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PONEResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PONEResponse) ProtoMessage() {}

func (x *PONEResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_heartbeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PONEResponse.ProtoReflect.Descriptor instead.
func (*PONEResponse) Descriptor() ([]byte, []int) {
	return file_heartbeat_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *PONEResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_heartbeat_heartbeat_proto protoreflect.FileDescriptor

var file_heartbeat_heartbeat_proto_rawDesc = []byte{
	0x0a, 0x19, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2f, 0x68, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x28, 0x0a, 0x0c, 0x50, 0x4f, 0x4e, 0x45, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x58, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x4b, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x45,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x68, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x2e, 0x50, 0x4f, 0x4e, 0x45, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x68, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x42, 0x19, 0x5a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x3b, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_heartbeat_heartbeat_proto_rawDescOnce sync.Once
	file_heartbeat_heartbeat_proto_rawDescData = file_heartbeat_heartbeat_proto_rawDesc
)

func file_heartbeat_heartbeat_proto_rawDescGZIP() []byte {
	file_heartbeat_heartbeat_proto_rawDescOnce.Do(func() {
		file_heartbeat_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_heartbeat_heartbeat_proto_rawDescData)
	})
	return file_heartbeat_heartbeat_proto_rawDescData
}

var file_heartbeat_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_heartbeat_heartbeat_proto_goTypes = []interface{}{
	(*PONEResponse)(nil),  // 0: heartbeat.PONEResponse
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_heartbeat_heartbeat_proto_depIdxs = []int32{
	1, // 0: heartbeat.Heartbeat.PONE:input_type -> google.protobuf.Empty
	0, // 1: heartbeat.Heartbeat.PONE:output_type -> heartbeat.PONEResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heartbeat_heartbeat_proto_init() }
func file_heartbeat_heartbeat_proto_init() {
	if File_heartbeat_heartbeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_heartbeat_heartbeat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PONEResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_heartbeat_heartbeat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heartbeat_heartbeat_proto_goTypes,
		DependencyIndexes: file_heartbeat_heartbeat_proto_depIdxs,
		MessageInfos:      file_heartbeat_heartbeat_proto_msgTypes,
	}.Build()
	File_heartbeat_heartbeat_proto = out.File
	file_heartbeat_heartbeat_proto_rawDesc = nil
	file_heartbeat_heartbeat_proto_goTypes = nil
	file_heartbeat_heartbeat_proto_depIdxs = nil
}
