// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	App           *App                   `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Server        *Server                `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Jwt           *Jwt                   `protobuf:"bytes,5,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Datetime      *Datetime              `protobuf:"bytes,6,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Language      *Language              `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	Validator     *Validator             `protobuf:"bytes,8,opt,name=validator,proto3" json:"validator,omitempty"`
	Log           *Log                   `protobuf:"bytes,9,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Bootstrap) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetJwt() *Jwt {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *Bootstrap) GetDatetime() *Datetime {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *Bootstrap) GetLanguage() *Language {
	if x != nil {
		return x.Language
	}
	return nil
}

func (x *Bootstrap) GetValidator() *Validator {
	if x != nil {
		return x.Validator
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *App) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type DatabaseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsn           string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Dbname        string                 `protobuf:"bytes,3,opt,name=dbname,proto3" json:"dbname,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Charset       string                 `protobuf:"bytes,7,opt,name=charset,proto3" json:"charset,omitempty"`
	Port          int64                  `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"`
	Prefix        string                 `protobuf:"bytes,9,opt,name=prefix,proto3" json:"prefix,omitempty"`
	MaxIdleConn   int64                  `protobuf:"varint,10,opt,name=max_idle_conn,json=maxIdleConn,proto3" json:"max_idle_conn,omitempty"`
	MaxOpenConn   int64                  `protobuf:"varint,11,opt,name=max_open_conn,json=maxOpenConn,proto3" json:"max_open_conn,omitempty"`
	MaxLifeTime   int64                  `protobuf:"varint,12,opt,name=max_life_time,json=maxLifeTime,proto3" json:"max_life_time,omitempty"`
	ParseTime     string                 `protobuf:"bytes,13,opt,name=parse_time,json=parseTime,proto3" json:"parse_time,omitempty"`
	Loc           string                 `protobuf:"bytes,14,opt,name=loc,proto3" json:"loc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseItem) Reset() {
	*x = DatabaseItem{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseItem) ProtoMessage() {}

func (x *DatabaseItem) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseItem.ProtoReflect.Descriptor instead.
func (*DatabaseItem) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *DatabaseItem) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *DatabaseItem) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *DatabaseItem) GetDbname() string {
	if x != nil {
		return x.Dbname
	}
	return ""
}

func (x *DatabaseItem) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DatabaseItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DatabaseItem) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DatabaseItem) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *DatabaseItem) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DatabaseItem) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *DatabaseItem) GetMaxIdleConn() int64 {
	if x != nil {
		return x.MaxIdleConn
	}
	return 0
}

func (x *DatabaseItem) GetMaxOpenConn() int64 {
	if x != nil {
		return x.MaxOpenConn
	}
	return 0
}

func (x *DatabaseItem) GetMaxLifeTime() int64 {
	if x != nil {
		return x.MaxLifeTime
	}
	return 0
}

func (x *DatabaseItem) GetParseTime() string {
	if x != nil {
		return x.ParseTime
	}
	return ""
}

func (x *DatabaseItem) GetLoc() string {
	if x != nil {
		return x.Loc
	}
	return ""
}

type RedisItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Network            string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr               string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Port               int64                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username           string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password           string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Db                 int32                  `protobuf:"varint,6,opt,name=db,proto3" json:"db,omitempty"`
	MaxRetries         int32                  `protobuf:"varint,7,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	MinRetryBackoff    int64                  `protobuf:"varint,8,opt,name=min_retry_backoff,json=minRetryBackoff,proto3" json:"min_retry_backoff,omitempty"`
	MaxRetryBackoff    int64                  `protobuf:"varint,9,opt,name=max_retry_backoff,json=maxRetryBackoff,proto3" json:"max_retry_backoff,omitempty"`
	DialTimeout        int64                  `protobuf:"varint,10,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	ReadTimeout        int64                  `protobuf:"varint,11,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout       int64                  `protobuf:"varint,12,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	PoolFifo           bool                   `protobuf:"varint,13,opt,name=pool_fifo,json=poolFifo,proto3" json:"pool_fifo,omitempty"`
	PoolSize           int32                  `protobuf:"varint,14,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	MinIdleConns       int64                  `protobuf:"varint,15,opt,name=min_idle_conns,json=minIdleConns,proto3" json:"min_idle_conns,omitempty"`
	MaxConnAge         int64                  `protobuf:"varint,16,opt,name=max_conn_age,json=maxConnAge,proto3" json:"max_conn_age,omitempty"`
	PoolTimeout        int64                  `protobuf:"varint,17,opt,name=pool_timeout,json=poolTimeout,proto3" json:"pool_timeout,omitempty"`
	IdleTimeout        int64                  `protobuf:"varint,18,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	IdleCheckFrequency int64                  `protobuf:"varint,19,opt,name=idle_check_frequency,json=idleCheckFrequency,proto3" json:"idle_check_frequency,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RedisItem) Reset() {
	*x = RedisItem{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisItem) ProtoMessage() {}

func (x *RedisItem) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisItem.ProtoReflect.Descriptor instead.
func (*RedisItem) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *RedisItem) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *RedisItem) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RedisItem) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RedisItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RedisItem) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RedisItem) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *RedisItem) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RedisItem) GetMinRetryBackoff() int64 {
	if x != nil {
		return x.MinRetryBackoff
	}
	return 0
}

func (x *RedisItem) GetMaxRetryBackoff() int64 {
	if x != nil {
		return x.MaxRetryBackoff
	}
	return 0
}

func (x *RedisItem) GetDialTimeout() int64 {
	if x != nil {
		return x.DialTimeout
	}
	return 0
}

func (x *RedisItem) GetReadTimeout() int64 {
	if x != nil {
		return x.ReadTimeout
	}
	return 0
}

func (x *RedisItem) GetWriteTimeout() int64 {
	if x != nil {
		return x.WriteTimeout
	}
	return 0
}

func (x *RedisItem) GetPoolFifo() bool {
	if x != nil {
		return x.PoolFifo
	}
	return false
}

func (x *RedisItem) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *RedisItem) GetMinIdleConns() int64 {
	if x != nil {
		return x.MinIdleConns
	}
	return 0
}

func (x *RedisItem) GetMaxConnAge() int64 {
	if x != nil {
		return x.MaxConnAge
	}
	return 0
}

func (x *RedisItem) GetPoolTimeout() int64 {
	if x != nil {
		return x.PoolTimeout
	}
	return 0
}

func (x *RedisItem) GetIdleTimeout() int64 {
	if x != nil {
		return x.IdleTimeout
	}
	return 0
}

func (x *RedisItem) GetIdleCheckFrequency() int64 {
	if x != nil {
		return x.IdleCheckFrequency
	}
	return 0
}

type Jwt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwt) Reset() {
	*x = Jwt{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwt) ProtoMessage() {}

func (x *Jwt) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwt.ProtoReflect.Descriptor instead.
func (*Jwt) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *Jwt) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *Jwt) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Jwt) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type Datetime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	CstLayout     string                 `protobuf:"bytes,2,opt,name=cst_layout,json=cstLayout,proto3" json:"cst_layout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Datetime) Reset() {
	*x = Datetime{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Datetime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datetime) ProtoMessage() {}

func (x *Datetime) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datetime.ProtoReflect.Descriptor instead.
func (*Datetime) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *Datetime) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Datetime) GetCstLayout() string {
	if x != nil {
		return x.CstLayout
	}
	return ""
}

type Language struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Local         string                 `protobuf:"bytes,1,opt,name=local,proto3" json:"local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *Language) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

type Validator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	Tagname       string                 `protobuf:"bytes,2,opt,name=tagname,proto3" json:"tagname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validator) Reset() {
	*x = Validator{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *Validator) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Validator) GetTagname() string {
	if x != nil {
		return x.Tagname
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxSize       int32                  `protobuf:"varint,1,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MaxBackups    int32                  `protobuf:"varint,2,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	MaxAge        int32                  `protobuf:"varint,3,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	LocalTime     bool                   `protobuf:"varint,4,opt,name=local_time,json=localTime,proto3" json:"local_time,omitempty"`
	Compress      bool                   `protobuf:"varint,5,opt,name=compress,proto3" json:"compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *Log) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Log) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *Log) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Log) GetLocalTime() bool {
	if x != nil {
		return x.LocalTime
	}
	return false
}

func (x *Log) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Default       *DatabaseItem          `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Data_Database) GetDefault() *DatabaseItem {
	if x != nil {
		return x.Default
	}
	return nil
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Default       *RedisItem             `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Data_Redis) GetDefault() *RedisItem {
	if x != nil {
		return x.Default
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\n" +
	"api.config\x1a\x1egoogle/protobuf/duration.proto\"\x81\x03\n" +
	"\tBootstrap\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x12!\n" +
	"\x03app\x18\x02 \x01(\v2\x0f.api.config.AppR\x03app\x12*\n" +
	"\x06server\x18\x03 \x01(\v2\x12.api.config.ServerR\x06server\x12$\n" +
	"\x04data\x18\x04 \x01(\v2\x10.api.config.DataR\x04data\x12!\n" +
	"\x03jwt\x18\x05 \x01(\v2\x0f.api.config.JwtR\x03jwt\x120\n" +
	"\bdatetime\x18\x06 \x01(\v2\x14.api.config.DatetimeR\bdatetime\x120\n" +
	"\blanguage\x18\a \x01(\v2\x14.api.config.LanguageR\blanguage\x123\n" +
	"\tvalidator\x18\b \x01(\v2\x15.api.config.ValidatorR\tvalidator\x12!\n" +
	"\x03log\x18\t \x01(\v2\x0f.api.config.LogR\x03log\"C\n" +
	"\x03App\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.api.config.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.api.config.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xe5\x01\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.api.config.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.api.config.Data.RedisR\x05redis\x1a>\n" +
	"\bDatabase\x122\n" +
	"\adefault\x18\x01 \x01(\v2\x18.api.config.DatabaseItemR\adefault\x1a8\n" +
	"\x05Redis\x12/\n" +
	"\adefault\x18\x01 \x01(\v2\x15.api.config.RedisItemR\adefault\"\xff\x02\n" +
	"\fDatabaseItem\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x16\n" +
	"\x06dbname\x18\x03 \x01(\tR\x06dbname\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x18\n" +
	"\acharset\x18\a \x01(\tR\acharset\x12\x12\n" +
	"\x04port\x18\b \x01(\x03R\x04port\x12\x16\n" +
	"\x06prefix\x18\t \x01(\tR\x06prefix\x12\"\n" +
	"\rmax_idle_conn\x18\n" +
	" \x01(\x03R\vmaxIdleConn\x12\"\n" +
	"\rmax_open_conn\x18\v \x01(\x03R\vmaxOpenConn\x12\"\n" +
	"\rmax_life_time\x18\f \x01(\x03R\vmaxLifeTime\x12\x1d\n" +
	"\n" +
	"parse_time\x18\r \x01(\tR\tparseTime\x12\x10\n" +
	"\x03loc\x18\x0e \x01(\tR\x03loc\"\xf3\x04\n" +
	"\tRedisItem\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x03R\x04port\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x06 \x01(\x05R\x02db\x12\x1f\n" +
	"\vmax_retries\x18\a \x01(\x05R\n" +
	"maxRetries\x12*\n" +
	"\x11min_retry_backoff\x18\b \x01(\x03R\x0fminRetryBackoff\x12*\n" +
	"\x11max_retry_backoff\x18\t \x01(\x03R\x0fmaxRetryBackoff\x12!\n" +
	"\fdial_timeout\x18\n" +
	" \x01(\x03R\vdialTimeout\x12!\n" +
	"\fread_timeout\x18\v \x01(\x03R\vreadTimeout\x12#\n" +
	"\rwrite_timeout\x18\f \x01(\x03R\fwriteTimeout\x12\x1b\n" +
	"\tpool_fifo\x18\r \x01(\bR\bpoolFifo\x12\x1b\n" +
	"\tpool_size\x18\x0e \x01(\x05R\bpoolSize\x12$\n" +
	"\x0emin_idle_conns\x18\x0f \x01(\x03R\fminIdleConns\x12 \n" +
	"\fmax_conn_age\x18\x10 \x01(\x03R\n" +
	"maxConnAge\x12!\n" +
	"\fpool_timeout\x18\x11 \x01(\x03R\vpoolTimeout\x12!\n" +
	"\fidle_timeout\x18\x12 \x01(\x03R\vidleTimeout\x120\n" +
	"\x14idle_check_frequency\x18\x13 \x01(\x03R\x12idleCheckFrequency\"A\n" +
	"\x03Jwt\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\"E\n" +
	"\bDatetime\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"cst_layout\x18\x02 \x01(\tR\tcstLayout\" \n" +
	"\bLanguage\x12\x14\n" +
	"\x05local\x18\x01 \x01(\tR\x05local\"=\n" +
	"\tValidator\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x12\x18\n" +
	"\atagname\x18\x02 \x01(\tR\atagname\"\x95\x01\n" +
	"\x03Log\x12\x19\n" +
	"\bmax_size\x18\x01 \x01(\x05R\amaxSize\x12\x1f\n" +
	"\vmax_backups\x18\x02 \x01(\x05R\n" +
	"maxBackups\x12\x17\n" +
	"\amax_age\x18\x03 \x01(\x05R\x06maxAge\x12\x1d\n" +
	"\n" +
	"local_time\x18\x04 \x01(\bR\tlocalTime\x12\x1a\n" +
	"\bcompress\x18\x05 \x01(\bR\bcompressB\x13Z\x11api/config;configb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_config_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: api.config.Bootstrap
	(*App)(nil),                 // 1: api.config.App
	(*Server)(nil),              // 2: api.config.Server
	(*Data)(nil),                // 3: api.config.Data
	(*DatabaseItem)(nil),        // 4: api.config.DatabaseItem
	(*RedisItem)(nil),           // 5: api.config.RedisItem
	(*Jwt)(nil),                 // 6: api.config.Jwt
	(*Datetime)(nil),            // 7: api.config.Datetime
	(*Language)(nil),            // 8: api.config.Language
	(*Validator)(nil),           // 9: api.config.Validator
	(*Log)(nil),                 // 10: api.config.Log
	(*Server_HTTP)(nil),         // 11: api.config.Server.HTTP
	(*Server_GRPC)(nil),         // 12: api.config.Server.GRPC
	(*Data_Database)(nil),       // 13: api.config.Data.Database
	(*Data_Redis)(nil),          // 14: api.config.Data.Redis
	(*durationpb.Duration)(nil), // 15: google.protobuf.Duration
}
var file_config_proto_depIdxs = []int32{
	1,  // 0: api.config.Bootstrap.app:type_name -> api.config.App
	2,  // 1: api.config.Bootstrap.server:type_name -> api.config.Server
	3,  // 2: api.config.Bootstrap.data:type_name -> api.config.Data
	6,  // 3: api.config.Bootstrap.jwt:type_name -> api.config.Jwt
	7,  // 4: api.config.Bootstrap.datetime:type_name -> api.config.Datetime
	8,  // 5: api.config.Bootstrap.language:type_name -> api.config.Language
	9,  // 6: api.config.Bootstrap.validator:type_name -> api.config.Validator
	10, // 7: api.config.Bootstrap.log:type_name -> api.config.Log
	11, // 8: api.config.Server.http:type_name -> api.config.Server.HTTP
	12, // 9: api.config.Server.grpc:type_name -> api.config.Server.GRPC
	13, // 10: api.config.Data.database:type_name -> api.config.Data.Database
	14, // 11: api.config.Data.redis:type_name -> api.config.Data.Redis
	15, // 12: api.config.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	15, // 13: api.config.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	4,  // 14: api.config.Data.Database.default:type_name -> api.config.DatabaseItem
	5,  // 15: api.config.Data.Redis.default:type_name -> api.config.RedisItem
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
