// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"mt/config"
	"mt/internal/biz"
	"mt/internal/data"
	"mt/internal/server"
	"mt/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(configServer *config.Server, configData *config.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(configData, logger)
	if err != nil {
		return nil, nil, err
	}
	heartbeatRepo := data.NewHeartbeatRepo(dataData, logger)
	heartbeatUsecase := biz.NewHeartbeatUsecase(heartbeatRepo, logger)
	heartbeatService := service.NewHeartbeatService(heartbeatUsecase)
	grpcServer := server.NewGRPCServer(configServer, heartbeatService, logger)
	httpServer := server.NewHTTPServer(configServer, heartbeatService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
